---
# tasks file to pull docker image from dockerhub
# and deploy it to stage

- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: 
    - docker.io
    - apt-transport-https
    - ca-certificates
    - python3-pip
    - python3-setuptools

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Log into DockerHub
  docker_login:
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    email: al.n.popov@gmail.com
    reauthorize: yes

- name: Pull an Image
  docker_image:
    name: alnp/java-app-project
    source: pull

- name: Start App Container
  docker_container:
    name: java_app
    image: alnp/java_app_project
    published_ports:
      - "8080:8080"